<?php
$modversion['name'] = _MI_MYMENU_NAME;
$modversion['version'] = 1.20;
$modversion['description'] = _MI_MYMENU_DESC;
$modversion['author'] = "Marcel Widmer<br>( http://www.coaching-forum.net/ )";
$modversion['credits'] = "The XOOPS Project";
$modversion['help'] = "mymenu.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "mymenulogo.gif";
$modversion['dirname'] = "mymenu";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "mymenu";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "mymenu.php";
$modversion['blocks'][1]['name'] = _MI_MYMENU_BNAME;
$modversion['blocks'][1]['description'] = "Zeigt individuelles Menu an";
$modversion['blocks'][1]['show_func'] = "block_MYMENU_show";

// Menu
$modversion['hasMain'] = 0;
?>