<html>
<head>
<title><? echo htmlspecialchars($title); ?></title>
<META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=iso-8859-15">
<LINK REL="stylesheet" TYPE="text/css" HREF="<? echo $stylesheet; ?>">
<link rel="shortcut icon" href="/JEDI.ico" />
<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"><!-- recaptcha ajax js --></script>
<script type="text/javascript" src="/dynamic.js"><!-- dynamic js --></script>
</head>

