<HTML>
<HEAD>
  <TITLE><? echo htmlspecialchars($title); ?></TITLE>
  <META HTTP-EQUIV="Content-type" CONTENT="text/html; charset=iso-8859-15">
  <META HTTP-EQUIV="expires" CONTENT="0">
  <META HTTP-EQUIV="pragma" CONTENT="no-cache">
  <META HTTP-EQUIV="cache-control" CONTENT="no-cache">
  <LINK REL="stylesheet" TYPE="text/css" HREF="<? echo $stylesheet; ?>">
  <link rel="shortcut icon" href="/JEDI.ico" />
</HEAD>
<BODY BGCOLOR="#FFFFFF">

