<?php
//  ------------------------------------------------------------------------ //
//                     Document Management System                            //
//                  Written By:  Brian E. Reifsnyder                         //
//                         Copyright (c) 2003                                //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = "Document Management System";
$modversion['version'] = 0.5;
$modversion['description'] = "Document Management System";
$modversion['credits'] = "Brian E. Reifsnyder";
$modversion['author'] = "";
$modversion['help'] = "";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = "No";
$modversion['image'] = "images/logo.png";
$modversion['dirname'] = "dms";
$modversion['hasMain'] = 1;
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0]  = "dms_config";
$modversion['tables'][1]  = "dms_file_sys_counters";
$modversion['tables'][2]  = "dms_objects";
$modversion['tables'][3]  = "dms_object_perms";
$modversion['tables'][4]  = "dms_object_versions";
$modversion['tables'][5]  = "dms_object_properties";
$modversion['tables'][6]  = "dms_exp_folders";
$modversion['tables'][7]  = "dms_active_folder";
$modversion['tables'][8]  = "dms_template_objects";
$modversion['tables'][9]  = "dms_lifecycles";
$modversion['tables'][10] = "dms_lifecycle_stages";
$modversion['tables'][11] = "dms_lifecycle_apply_perms";
$modversion['tables'][12] = "dms_lifecycle_doc_perms";
